# WeBookClient AppVeyor configuration files
image: Visual Studio 2019

environment:
  global:
    BIN: WeBookClient
    MY_ENV: AppVeyor
    QIF_PACKAGE_URI: 'packages\com.lightwizzard.WeBookClient\data'
  matrix:  
    - ARCH: x64
      COMPILER: MinGW
      QTDIR: C:\Qt\5.14.2\mingw73_64  
  
install:
  - choco install -y InnoSetup
  - cinst mingw
  - set PATH=%QTDIR%\bin;%PATH%;"C:\Program Files (x86)\Inno Setup 5"

configuration:
  - release
  #- debug
platform:
  - x64
  #- Win32

build_script:
  - qmake %BIN%.pro CONFIG+=static
  - mingw32-make

after_build:
  - dir /b /s *.exe
  - mkdir deploy
  - copy "%APPVEYOR_BUILD_FOLDER%\%CONFIGURATION%\%BIN%.exe" "deploy\%BIN%.exe"
  - windeployqt "deploy/%BIN%.exe" --verbose=2
  - for %%I in (%PRJLIBS%) do copy %PRJLIBDIR%\%%I deploy\
  - 7z a -r -tzip "%BIN%-%CONFIGURATION%.zip" deploy\*
  - echo APPVEYOR_BUILD_FOLDER=%APPVEYOR_BUILD_FOLDER%
  - if exist C:\projects\ (echo C:\projects exists)
  - if exist C:\projects\ (dir )
  - if exist C:\projects\ (dir C:\projects\)
  - if exist C:\projects\ (dir "%APPVEYOR_BUILD_FOLDER%\")
  - if exist C:\projects\ (dir "%APPVEYOR_BUILD_FOLDER%\deploy\")
  - if exist C:\Qt\QtIFW-3.1.1\ (dir C:\Qt\QtIFW-3.1.1)
  - if exist C:\Qt\QtIFW-3.1.1\bin\ (dir C:\Qt\QtIFW-3.1.1\bin\)
  - if exist C:\Qt\QtIFW-3.1.1\bin\binarycreator.exe (echo C:\Qt\QtIFW-3.1.1\bin\binarycreator.exe exists) else (echo C:\Qt\QtIFW-3.1.1\bin\binarycreator.exe does not exists)
  - xcopy /s /e /f "%APPVEYOR_BUILD_FOLDER%\deploy" "%APPVEYOR_BUILD_FOLDER%\%QIF_PACKAGE_URI%"
  - C:\Qt\Tools\QtInstallerFramework\3.2\bin\binarycreator.exe --offline-only -c "%APPVEYOR_BUILD_FOLDER%\config\config.xml" -p "%APPVEYOR_BUILD_FOLDER%\packages" "%BIN%-Installer.exe"
  - 7z a -tzip "%BIN%-Installer.zip" "%BIN%-Installer.exe"
  - dir /b /s *.zip
  - dir /b /s *.exe
  - dir
  - echo Completed
  
artifacts:
  - path: '%BIN%-%CONFIGURATION%.zip'
    name: 'Zip-%CONFIGURATION%'
  - path: '%BIN%-Installer.zip'  
    name: 'ZipInstaller'
  - path: '%BIN%-Installer.exe'
    name: 'ExecutableFile'

deploy:
  - provider: GitHub
    release: continuous
    artifact: 'Zip-%CONFIGURATION%'
    draft: false
    prerelease: true
    auth_token:
      secure: zhMbBtnPhVjygBTfOpQniE0jUPWOLewzUCFmEQIqZ/VSfFGpdzh+ZPeDU03rP1yD
  - provider: GitHub
    release: continuous
    artifact: 'ZipInstaller'
    draft: false
    prerelease: true
    auth_token:
      secure: zhMbBtnPhVjygBTfOpQniE0jUPWOLewzUCFmEQIqZ/VSfFGpdzh+ZPeDU03rP1yD
  - provider: GitHub
    release: continuous
    artifact: 'ExecutableFile'
    draft: false
    prerelease: true
    auth_token:
      secure: zhMbBtnPhVjygBTfOpQniE0jUPWOLewzUCFmEQIqZ/VSfFGpdzh+ZPeDU03rP1yD
############################################## End of File ####################
