#############################################################################
# Makefile for building: build/debug/WeBookClient
# Generated by qmake (3.1) (Qt 5.15.0)
# Project:  WeBookClient.pro
# Template: app
# Command: /usr/bin/qmake -o Makefile WeBookClient.pro
#############################################################################

MAKEFILE      = Makefile

EQ            = =

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DAPP_VERSION=\"0.1.0\" -DQT_DEPRECATED_WARNINGS -DQT_NO_DEBUG -DQT_PRINTSUPPORT_LIB -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -O2 -Wall -Wextra -D_REENTRANT -fPIC $(DEFINES)
CXXFLAGS      = -pipe -O2 -std=gnu++1z -Wall -Wextra -D_REENTRANT -fPIC $(DEFINES)
INCPATH       = -I. -I. -Isrc -I${QT_INSTALL_LIBS}/qt -Isrc/QtAES -isystem /usr/include/qt -isystem /usr/include/qt/QtPrintSupport -isystem /usr/include/qt/QtWidgets -isystem /usr/include/qt/QtGui -isystem /usr/include/qt/QtNetwork -isystem /usr/include/qt/QtCore -Ibuild/debug/moc -Ibuild/debug/ui -I/usr/lib/qt/mkspecs/linux-g++
QMAKE         = /usr/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
QINSTALL      = /usr/bin/qmake -install qinstall
QINSTALL_PROGRAM = /usr/bin/qmake -install qinstall -exe
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = WeBookClient0.1.0
DISTDIR = /mnt/qnap-light-wizzard/workspace/WeBook/projects/WeBookClient/build/debug/obj/WeBookClient0.1.0
LINK          = g++
LFLAGS        = -Wl,-O1
LIBS          = $(SUBLIBS) /usr/lib/libQt5PrintSupport.so /usr/lib/libQt5Widgets.so /usr/lib/libQt5Gui.so /usr/lib/libQt5Network.so /usr/lib/libQt5Core.so -lGL -lpthread   
AR            = ar cqs
RANLIB        = 
SED           = sed
STRIP         = strip

####### Output directory

OBJECTS_DIR   = build/debug/obj/

####### Files

SOURCES       = src/AboutDialog.cpp \
		src/MainWindow.cpp \
		src/WeBookMan.cpp \
		src/TreeItem.cpp \
		src/TreeModel.cpp \
		src/TreeViewDragDropModel.cpp \
		src/main.cpp \
		src/QLogger/QLoggerManager.cpp \
		src/QLogger/QLoggerWriter.cpp \
		src/QLogger/QLoggerCommon.cpp \
		src/QLogger/QLoggerCrypto.cpp \
		src/QtAES/QAESEncryption.cpp build/debug/qrc/qrc_WeBookClient.cpp \
		build/debug/moc/moc_AboutDialog.cpp \
		build/debug/moc/moc_MainWindow.cpp \
		build/debug/moc/moc_WeBookMan.cpp \
		build/debug/moc/moc_TreeModel.cpp \
		build/debug/moc/moc_TreeViewDragDropModel.cpp \
		build/debug/moc/moc_QLoggerLevel.cpp \
		build/debug/moc/moc_QLoggerWriter.cpp \
		build/debug/moc/moc_QLoggerCommon.cpp \
		build/debug/moc/moc_QLoggerCrypto.cpp \
		build/debug/moc/moc_QAESEncryption.cpp
OBJECTS       = build/debug/obj/AboutDialog.o \
		build/debug/obj/MainWindow.o \
		build/debug/obj/WeBookMan.o \
		build/debug/obj/TreeItem.o \
		build/debug/obj/TreeModel.o \
		build/debug/obj/TreeViewDragDropModel.o \
		build/debug/obj/main.o \
		build/debug/obj/QLoggerManager.o \
		build/debug/obj/QLoggerWriter.o \
		build/debug/obj/QLoggerCommon.o \
		build/debug/obj/QLoggerCrypto.o \
		build/debug/obj/QAESEncryption.o \
		build/debug/obj/qrc_WeBookClient.o \
		build/debug/obj/moc_AboutDialog.o \
		build/debug/obj/moc_MainWindow.o \
		build/debug/obj/moc_WeBookMan.o \
		build/debug/obj/moc_TreeModel.o \
		build/debug/obj/moc_TreeViewDragDropModel.o \
		build/debug/obj/moc_QLoggerLevel.o \
		build/debug/obj/moc_QLoggerWriter.o \
		build/debug/obj/moc_QLoggerCommon.o \
		build/debug/obj/moc_QLoggerCrypto.o \
		build/debug/obj/moc_QAESEncryption.o
DIST          = .appveyor.yml \
		.travis.yml \
		WeBookClient.doxygen \
		src/QtAES/Readme.md \
		WeBookClient.qdocconf \
		data/WeBookClient.ini \
		data/WeBook.toc \
		data/WeBooks.cat \
		README.md \
		/usr/lib/qt/mkspecs/features/spec_pre.prf \
		/usr/lib/qt/mkspecs/common/unix.conf \
		/usr/lib/qt/mkspecs/common/linux.conf \
		/usr/lib/qt/mkspecs/common/sanitize.conf \
		/usr/lib/qt/mkspecs/common/gcc-base.conf \
		/usr/lib/qt/mkspecs/common/gcc-base-unix.conf \
		/usr/lib/qt/mkspecs/common/g++-base.conf \
		/usr/lib/qt/mkspecs/common/g++-unix.conf \
		/usr/lib/qt/mkspecs/qconfig.pri \
		/usr/lib/qt/mkspecs/modules/qt_Attica.pri \
		/usr/lib/qt/mkspecs/modules/qt_KActivities.pri \
		/usr/lib/qt/mkspecs/modules/qt_KArchive.pri \
		/usr/lib/qt/mkspecs/modules/qt_KAuth.pri \
		/usr/lib/qt/mkspecs/modules/qt_KAuthCore.pri \
		/usr/lib/qt/mkspecs/modules/qt_KBookmarks.pri \
		/usr/lib/qt/mkspecs/modules/qt_KCodecs.pri \
		/usr/lib/qt/mkspecs/modules/qt_KCompletion.pri \
		/usr/lib/qt/mkspecs/modules/qt_KConfigCore.pri \
		/usr/lib/qt/mkspecs/modules/qt_KConfigGui.pri \
		/usr/lib/qt/mkspecs/modules/qt_KConfigWidgets.pri \
		/usr/lib/qt/mkspecs/modules/qt_KCoreAddons.pri \
		/usr/lib/qt/mkspecs/modules/qt_KCrash.pri \
		/usr/lib/qt/mkspecs/modules/qt_KDBusAddons.pri \
		/usr/lib/qt/mkspecs/modules/qt_KDNSSD.pri \
		/usr/lib/qt/mkspecs/modules/qt_KGlobalAccel.pri \
		/usr/lib/qt/mkspecs/modules/qt_KGuiAddons.pri \
		/usr/lib/qt/mkspecs/modules/qt_KI18n.pri \
		/usr/lib/qt/mkspecs/modules/qt_KIconThemes.pri \
		/usr/lib/qt/mkspecs/modules/qt_KIdleTime.pri \
		/usr/lib/qt/mkspecs/modules/qt_KIOCore.pri \
		/usr/lib/qt/mkspecs/modules/qt_KIOFileWidgets.pri \
		/usr/lib/qt/mkspecs/modules/qt_KIOGui.pri \
		/usr/lib/qt/mkspecs/modules/qt_KIOWidgets.pri \
		/usr/lib/qt/mkspecs/modules/qt_KItemModels.pri \
		/usr/lib/qt/mkspecs/modules/qt_KItemViews.pri \
		/usr/lib/qt/mkspecs/modules/qt_KJobWidgets.pri \
		/usr/lib/qt/mkspecs/modules/qt_KJS.pri \
		/usr/lib/qt/mkspecs/modules/qt_KJSApi.pri \
		/usr/lib/qt/mkspecs/modules/qt_KNotifications.pri \
		/usr/lib/qt/mkspecs/modules/qt_KNTLM.pri \
		/usr/lib/qt/mkspecs/modules/qt_KPlotting.pri \
		/usr/lib/qt/mkspecs/modules/qt_KService.pri \
		/usr/lib/qt/mkspecs/modules/qt_KSyntaxHighlighting.pri \
		/usr/lib/qt/mkspecs/modules/qt_KTextWidgets.pri \
		/usr/lib/qt/mkspecs/modules/qt_KWallet.pri \
		/usr/lib/qt/mkspecs/modules/qt_KWaylandClient.pri \
		/usr/lib/qt/mkspecs/modules/qt_KWaylandServer.pri \
		/usr/lib/qt/mkspecs/modules/qt_KWidgetsAddons.pri \
		/usr/lib/qt/mkspecs/modules/qt_KWindowSystem.pri \
		/usr/lib/qt/mkspecs/modules/qt_KXmlGui.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_3danimation.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_3danimation_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_3dcore.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_3dcore_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_3dextras.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_3dextras_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_3dinput.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_3dinput_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_3dlogic.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_3dlogic_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_3dquick.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_3dquick_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_3dquickanimation.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_3dquickanimation_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_3dquickextras.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_3dquickextras_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_3dquickinput.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_3dquickinput_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_3dquickrender.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_3dquickrender_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_3dquickscene2d.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_3dquickscene2d_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_3drender.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_3drender_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_bluetooth.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_bluetooth_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_charts.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_charts_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_core.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_core_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_dbus.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_designer.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_designer_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_designercomponents_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_edid_support_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_egl_support_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_fb_support_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_gamepad.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_gamepad_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_glx_support_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_gui.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_help.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_help_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_httpserver.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_httpserver_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_input_support_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_kms_support_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_location.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_location_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_multimedia.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_multimedia_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_multimediagsttools_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_multimediawidgets.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_network.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_network_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_networkauth.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_networkauth_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_nfc.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_nfc_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_opengl.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_openglextensions.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_pdf.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_pdf_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_pdfwidgets.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_pdfwidgets_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_positioning.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_positioning_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_positioningquick.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_positioningquick_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_qml.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_qml_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_qmldebug_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_qmlmodels.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_qmlmodels_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_qmltest.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_qmltest_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_qmlworkerscript.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_qmlworkerscript_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_quick.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_quick_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_quickcontrols2.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_quickparticles_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_quickshapes_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_quicktemplates2.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_quickwidgets.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_script.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_script_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_scripttools.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_scripttools_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_sensors.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_sensors_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_service.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_service_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_service_support_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_sql.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_sslserver.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_sslserver_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_svg.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_svg_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_testlib.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_texttospeech.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_texttospeech_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_theme_support_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_uiplugin.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_uitools.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_uitools_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_vulkan_support_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_waylandclient.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_waylandclient_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_waylandcompositor.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_waylandcompositor_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_webchannel.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_webchannel_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_webengine.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_webengine_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_webenginecore.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_webenginecore_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_webenginewidgets.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_webenginewidgets_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_webkit.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_webkit_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_webkitwidgets.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_webkitwidgets_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_websockets.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_websockets_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_widgets.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_x11extras.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_x11extras_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_xkbcommon_support_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_xml.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_xmlpatterns.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_phonon4qt5.pri \
		/usr/lib/qt/mkspecs/modules/qt_Solid.pri \
		/usr/lib/qt/mkspecs/modules/qt_SonnetCore.pri \
		/usr/lib/qt/mkspecs/modules/qt_SonnetUi.pri \
		/usr/lib/qt/mkspecs/modules/qt_ThreadWeaver.pri \
		/usr/lib/qt/mkspecs/features/qt_functions.prf \
		/usr/lib/qt/mkspecs/features/qt_config.prf \
		/usr/lib/qt/mkspecs/linux-g++/qmake.conf \
		/usr/lib/qt/mkspecs/features/spec_post.prf \
		../../.qmake.stash \
		/usr/lib/qt/mkspecs/features/exclusive_builds.prf \
		/usr/lib/qt/mkspecs/features/toolchain.prf \
		/usr/lib/qt/mkspecs/features/default_pre.prf \
		/usr/lib/qt/mkspecs/features/resolve_config.prf \
		/usr/lib/qt/mkspecs/features/default_post.prf \
		/usr/lib/qt/mkspecs/features/warn_on.prf \
		/usr/lib/qt/mkspecs/features/qt.prf \
		/usr/lib/qt/mkspecs/features/resources_functions.prf \
		/usr/lib/qt/mkspecs/features/resources.prf \
		/usr/lib/qt/mkspecs/features/moc.prf \
		/usr/lib/qt/mkspecs/features/unix/opengl.prf \
		/usr/lib/qt/mkspecs/features/uic.prf \
		/usr/lib/qt/mkspecs/features/unix/thread.prf \
		/usr/lib/qt/mkspecs/features/qmake_use.prf \
		/usr/lib/qt/mkspecs/features/file_copies.prf \
		/usr/lib/qt/mkspecs/features/testcase_targets.prf \
		/usr/lib/qt/mkspecs/features/exceptions.prf \
		/usr/lib/qt/mkspecs/features/yacc.prf \
		/usr/lib/qt/mkspecs/features/lex.prf \
		WeBookClient.pro src/AboutDialog.h \
		src/MainWindow.h \
		src/WeBookMan.h \
		src/TreeItem.h \
		src/TreeModel.h \
		src/TreeViewDragDropModel.h \
		src/QLogger/QLoggerLevel.h \
		src/QLogger/QLoggerConstants.h \
		src/QLogger/QLoggerManager.h \
		src/QLogger/QLoggerWriter.h \
		src/QLogger/QLoggerCommon.h \
		src/QLogger/QLoggerCrypto.h \
		src/QtAES/QAESEncryption.h src/AboutDialog.cpp \
		src/MainWindow.cpp \
		src/WeBookMan.cpp \
		src/TreeItem.cpp \
		src/TreeModel.cpp \
		src/TreeViewDragDropModel.cpp \
		src/main.cpp \
		src/QLogger/QLoggerManager.cpp \
		src/QLogger/QLoggerWriter.cpp \
		src/QLogger/QLoggerCommon.cpp \
		src/QLogger/QLoggerCrypto.cpp \
		src/QtAES/QAESEncryption.cpp
QMAKE_TARGET  = WeBookClient
DESTDIR       = build/debug/
TARGET        = build/debug/WeBookClient


first: all
####### Build rules

build/debug/WeBookClient: build/debug/ui/ui_MainWindow.h build/debug/ui/ui_AboutDialog.h $(OBJECTS)  
	@test -d build/debug/ || mkdir -p build/debug/
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: WeBookClient.pro /usr/lib/qt/mkspecs/linux-g++/qmake.conf /usr/lib/qt/mkspecs/features/spec_pre.prf \
		/usr/lib/qt/mkspecs/common/unix.conf \
		/usr/lib/qt/mkspecs/common/linux.conf \
		/usr/lib/qt/mkspecs/common/sanitize.conf \
		/usr/lib/qt/mkspecs/common/gcc-base.conf \
		/usr/lib/qt/mkspecs/common/gcc-base-unix.conf \
		/usr/lib/qt/mkspecs/common/g++-base.conf \
		/usr/lib/qt/mkspecs/common/g++-unix.conf \
		/usr/lib/qt/mkspecs/qconfig.pri \
		/usr/lib/qt/mkspecs/modules/qt_Attica.pri \
		/usr/lib/qt/mkspecs/modules/qt_KActivities.pri \
		/usr/lib/qt/mkspecs/modules/qt_KArchive.pri \
		/usr/lib/qt/mkspecs/modules/qt_KAuth.pri \
		/usr/lib/qt/mkspecs/modules/qt_KAuthCore.pri \
		/usr/lib/qt/mkspecs/modules/qt_KBookmarks.pri \
		/usr/lib/qt/mkspecs/modules/qt_KCodecs.pri \
		/usr/lib/qt/mkspecs/modules/qt_KCompletion.pri \
		/usr/lib/qt/mkspecs/modules/qt_KConfigCore.pri \
		/usr/lib/qt/mkspecs/modules/qt_KConfigGui.pri \
		/usr/lib/qt/mkspecs/modules/qt_KConfigWidgets.pri \
		/usr/lib/qt/mkspecs/modules/qt_KCoreAddons.pri \
		/usr/lib/qt/mkspecs/modules/qt_KCrash.pri \
		/usr/lib/qt/mkspecs/modules/qt_KDBusAddons.pri \
		/usr/lib/qt/mkspecs/modules/qt_KDNSSD.pri \
		/usr/lib/qt/mkspecs/modules/qt_KGlobalAccel.pri \
		/usr/lib/qt/mkspecs/modules/qt_KGuiAddons.pri \
		/usr/lib/qt/mkspecs/modules/qt_KI18n.pri \
		/usr/lib/qt/mkspecs/modules/qt_KIconThemes.pri \
		/usr/lib/qt/mkspecs/modules/qt_KIdleTime.pri \
		/usr/lib/qt/mkspecs/modules/qt_KIOCore.pri \
		/usr/lib/qt/mkspecs/modules/qt_KIOFileWidgets.pri \
		/usr/lib/qt/mkspecs/modules/qt_KIOGui.pri \
		/usr/lib/qt/mkspecs/modules/qt_KIOWidgets.pri \
		/usr/lib/qt/mkspecs/modules/qt_KItemModels.pri \
		/usr/lib/qt/mkspecs/modules/qt_KItemViews.pri \
		/usr/lib/qt/mkspecs/modules/qt_KJobWidgets.pri \
		/usr/lib/qt/mkspecs/modules/qt_KJS.pri \
		/usr/lib/qt/mkspecs/modules/qt_KJSApi.pri \
		/usr/lib/qt/mkspecs/modules/qt_KNotifications.pri \
		/usr/lib/qt/mkspecs/modules/qt_KNTLM.pri \
		/usr/lib/qt/mkspecs/modules/qt_KPlotting.pri \
		/usr/lib/qt/mkspecs/modules/qt_KService.pri \
		/usr/lib/qt/mkspecs/modules/qt_KSyntaxHighlighting.pri \
		/usr/lib/qt/mkspecs/modules/qt_KTextWidgets.pri \
		/usr/lib/qt/mkspecs/modules/qt_KWallet.pri \
		/usr/lib/qt/mkspecs/modules/qt_KWaylandClient.pri \
		/usr/lib/qt/mkspecs/modules/qt_KWaylandServer.pri \
		/usr/lib/qt/mkspecs/modules/qt_KWidgetsAddons.pri \
		/usr/lib/qt/mkspecs/modules/qt_KWindowSystem.pri \
		/usr/lib/qt/mkspecs/modules/qt_KXmlGui.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_3danimation.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_3danimation_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_3dcore.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_3dcore_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_3dextras.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_3dextras_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_3dinput.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_3dinput_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_3dlogic.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_3dlogic_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_3dquick.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_3dquick_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_3dquickanimation.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_3dquickanimation_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_3dquickextras.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_3dquickextras_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_3dquickinput.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_3dquickinput_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_3dquickrender.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_3dquickrender_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_3dquickscene2d.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_3dquickscene2d_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_3drender.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_3drender_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_bluetooth.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_bluetooth_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_charts.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_charts_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_core.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_core_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_dbus.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_designer.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_designer_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_designercomponents_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_edid_support_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_egl_support_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_fb_support_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_gamepad.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_gamepad_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_glx_support_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_gui.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_help.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_help_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_httpserver.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_httpserver_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_input_support_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_kms_support_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_location.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_location_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_multimedia.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_multimedia_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_multimediagsttools_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_multimediawidgets.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_network.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_network_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_networkauth.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_networkauth_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_nfc.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_nfc_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_opengl.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_openglextensions.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_pdf.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_pdf_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_pdfwidgets.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_pdfwidgets_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_positioning.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_positioning_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_positioningquick.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_positioningquick_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_qml.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_qml_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_qmldebug_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_qmlmodels.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_qmlmodels_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_qmltest.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_qmltest_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_qmlworkerscript.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_qmlworkerscript_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_quick.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_quick_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_quickcontrols2.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_quickparticles_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_quickshapes_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_quicktemplates2.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_quickwidgets.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_script.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_script_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_scripttools.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_scripttools_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_sensors.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_sensors_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_service.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_service_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_service_support_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_sql.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_sslserver.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_sslserver_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_svg.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_svg_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_testlib.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_texttospeech.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_texttospeech_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_theme_support_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_uiplugin.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_uitools.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_uitools_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_vulkan_support_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_waylandclient.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_waylandclient_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_waylandcompositor.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_waylandcompositor_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_webchannel.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_webchannel_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_webengine.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_webengine_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_webenginecore.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_webenginecore_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_webenginewidgets.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_webenginewidgets_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_webkit.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_webkit_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_webkitwidgets.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_webkitwidgets_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_websockets.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_websockets_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_widgets.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_x11extras.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_x11extras_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_xkbcommon_support_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_xml.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_xmlpatterns.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_phonon4qt5.pri \
		/usr/lib/qt/mkspecs/modules/qt_Solid.pri \
		/usr/lib/qt/mkspecs/modules/qt_SonnetCore.pri \
		/usr/lib/qt/mkspecs/modules/qt_SonnetUi.pri \
		/usr/lib/qt/mkspecs/modules/qt_ThreadWeaver.pri \
		/usr/lib/qt/mkspecs/features/qt_functions.prf \
		/usr/lib/qt/mkspecs/features/qt_config.prf \
		/usr/lib/qt/mkspecs/linux-g++/qmake.conf \
		/usr/lib/qt/mkspecs/features/spec_post.prf \
		../../.qmake.stash \
		/usr/lib/qt/mkspecs/features/exclusive_builds.prf \
		/usr/lib/qt/mkspecs/features/toolchain.prf \
		/usr/lib/qt/mkspecs/features/default_pre.prf \
		/usr/lib/qt/mkspecs/features/resolve_config.prf \
		/usr/lib/qt/mkspecs/features/default_post.prf \
		/usr/lib/qt/mkspecs/features/warn_on.prf \
		/usr/lib/qt/mkspecs/features/qt.prf \
		/usr/lib/qt/mkspecs/features/resources_functions.prf \
		/usr/lib/qt/mkspecs/features/resources.prf \
		/usr/lib/qt/mkspecs/features/moc.prf \
		/usr/lib/qt/mkspecs/features/unix/opengl.prf \
		/usr/lib/qt/mkspecs/features/uic.prf \
		/usr/lib/qt/mkspecs/features/unix/thread.prf \
		/usr/lib/qt/mkspecs/features/qmake_use.prf \
		/usr/lib/qt/mkspecs/features/file_copies.prf \
		/usr/lib/qt/mkspecs/features/testcase_targets.prf \
		/usr/lib/qt/mkspecs/features/exceptions.prf \
		/usr/lib/qt/mkspecs/features/yacc.prf \
		/usr/lib/qt/mkspecs/features/lex.prf \
		WeBookClient.pro \
		WeBookClient.qrc
	$(QMAKE) -o Makefile WeBookClient.pro
/usr/lib/qt/mkspecs/features/spec_pre.prf:
/usr/lib/qt/mkspecs/common/unix.conf:
/usr/lib/qt/mkspecs/common/linux.conf:
/usr/lib/qt/mkspecs/common/sanitize.conf:
/usr/lib/qt/mkspecs/common/gcc-base.conf:
/usr/lib/qt/mkspecs/common/gcc-base-unix.conf:
/usr/lib/qt/mkspecs/common/g++-base.conf:
/usr/lib/qt/mkspecs/common/g++-unix.conf:
/usr/lib/qt/mkspecs/qconfig.pri:
/usr/lib/qt/mkspecs/modules/qt_Attica.pri:
/usr/lib/qt/mkspecs/modules/qt_KActivities.pri:
/usr/lib/qt/mkspecs/modules/qt_KArchive.pri:
/usr/lib/qt/mkspecs/modules/qt_KAuth.pri:
/usr/lib/qt/mkspecs/modules/qt_KAuthCore.pri:
/usr/lib/qt/mkspecs/modules/qt_KBookmarks.pri:
/usr/lib/qt/mkspecs/modules/qt_KCodecs.pri:
/usr/lib/qt/mkspecs/modules/qt_KCompletion.pri:
/usr/lib/qt/mkspecs/modules/qt_KConfigCore.pri:
/usr/lib/qt/mkspecs/modules/qt_KConfigGui.pri:
/usr/lib/qt/mkspecs/modules/qt_KConfigWidgets.pri:
/usr/lib/qt/mkspecs/modules/qt_KCoreAddons.pri:
/usr/lib/qt/mkspecs/modules/qt_KCrash.pri:
/usr/lib/qt/mkspecs/modules/qt_KDBusAddons.pri:
/usr/lib/qt/mkspecs/modules/qt_KDNSSD.pri:
/usr/lib/qt/mkspecs/modules/qt_KGlobalAccel.pri:
/usr/lib/qt/mkspecs/modules/qt_KGuiAddons.pri:
/usr/lib/qt/mkspecs/modules/qt_KI18n.pri:
/usr/lib/qt/mkspecs/modules/qt_KIconThemes.pri:
/usr/lib/qt/mkspecs/modules/qt_KIdleTime.pri:
/usr/lib/qt/mkspecs/modules/qt_KIOCore.pri:
/usr/lib/qt/mkspecs/modules/qt_KIOFileWidgets.pri:
/usr/lib/qt/mkspecs/modules/qt_KIOGui.pri:
/usr/lib/qt/mkspecs/modules/qt_KIOWidgets.pri:
/usr/lib/qt/mkspecs/modules/qt_KItemModels.pri:
/usr/lib/qt/mkspecs/modules/qt_KItemViews.pri:
/usr/lib/qt/mkspecs/modules/qt_KJobWidgets.pri:
/usr/lib/qt/mkspecs/modules/qt_KJS.pri:
/usr/lib/qt/mkspecs/modules/qt_KJSApi.pri:
/usr/lib/qt/mkspecs/modules/qt_KNotifications.pri:
/usr/lib/qt/mkspecs/modules/qt_KNTLM.pri:
/usr/lib/qt/mkspecs/modules/qt_KPlotting.pri:
/usr/lib/qt/mkspecs/modules/qt_KService.pri:
/usr/lib/qt/mkspecs/modules/qt_KSyntaxHighlighting.pri:
/usr/lib/qt/mkspecs/modules/qt_KTextWidgets.pri:
/usr/lib/qt/mkspecs/modules/qt_KWallet.pri:
/usr/lib/qt/mkspecs/modules/qt_KWaylandClient.pri:
/usr/lib/qt/mkspecs/modules/qt_KWaylandServer.pri:
/usr/lib/qt/mkspecs/modules/qt_KWidgetsAddons.pri:
/usr/lib/qt/mkspecs/modules/qt_KWindowSystem.pri:
/usr/lib/qt/mkspecs/modules/qt_KXmlGui.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_3danimation.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_3danimation_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_3dcore.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_3dcore_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_3dextras.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_3dextras_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_3dinput.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_3dinput_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_3dlogic.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_3dlogic_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_3dquick.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_3dquick_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_3dquickanimation.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_3dquickanimation_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_3dquickextras.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_3dquickextras_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_3dquickinput.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_3dquickinput_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_3dquickrender.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_3dquickrender_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_3dquickscene2d.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_3dquickscene2d_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_3drender.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_3drender_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_accessibility_support_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_bluetooth.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_bluetooth_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_bootstrap_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_charts.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_charts_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_concurrent.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_concurrent_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_core.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_core_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_dbus.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_dbus_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_designer.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_designer_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_designercomponents_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_devicediscovery_support_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_edid_support_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_egl_support_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_fb_support_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_fontdatabase_support_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_gamepad.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_gamepad_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_glx_support_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_gui.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_gui_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_help.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_help_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_httpserver.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_httpserver_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_input_support_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_kms_support_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_location.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_location_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_multimedia.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_multimedia_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_multimediagsttools_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_multimediawidgets.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_multimediawidgets_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_network.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_network_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_networkauth.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_networkauth_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_nfc.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_nfc_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_opengl.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_opengl_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_openglextensions.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_openglextensions_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_packetprotocol_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_pdf.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_pdf_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_pdfwidgets.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_pdfwidgets_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_platformcompositor_support_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_positioning.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_positioning_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_positioningquick.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_positioningquick_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_printsupport.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_printsupport_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_qml.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_qml_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_qmldebug_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_qmldevtools_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_qmlmodels.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_qmlmodels_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_qmltest.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_qmltest_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_qmlworkerscript.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_qmlworkerscript_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_quick.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_quick_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_quickcontrols2.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_quickcontrols2_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_quickparticles_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_quickshapes_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_quicktemplates2.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_quicktemplates2_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_quickwidgets.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_quickwidgets_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_script.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_script_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_scripttools.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_scripttools_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_sensors.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_sensors_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_service.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_service_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_service_support_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_sql.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_sql_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_sslserver.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_sslserver_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_svg.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_svg_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_testlib.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_testlib_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_texttospeech.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_texttospeech_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_theme_support_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_uiplugin.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_uitools.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_uitools_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_vulkan_support_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_waylandclient.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_waylandclient_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_waylandcompositor.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_waylandcompositor_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_webchannel.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_webchannel_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_webengine.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_webengine_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_webenginecore.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_webenginecore_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_webenginewidgets.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_webenginewidgets_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_webkit.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_webkit_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_webkitwidgets.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_webkitwidgets_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_websockets.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_websockets_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_widgets.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_widgets_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_x11extras.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_x11extras_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_xkbcommon_support_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_xml.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_xml_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_xmlpatterns.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_xmlpatterns_private.pri:
/usr/lib/qt/mkspecs/modules/qt_phonon4qt5.pri:
/usr/lib/qt/mkspecs/modules/qt_Solid.pri:
/usr/lib/qt/mkspecs/modules/qt_SonnetCore.pri:
/usr/lib/qt/mkspecs/modules/qt_SonnetUi.pri:
/usr/lib/qt/mkspecs/modules/qt_ThreadWeaver.pri:
/usr/lib/qt/mkspecs/features/qt_functions.prf:
/usr/lib/qt/mkspecs/features/qt_config.prf:
/usr/lib/qt/mkspecs/linux-g++/qmake.conf:
/usr/lib/qt/mkspecs/features/spec_post.prf:
../../.qmake.stash:
/usr/lib/qt/mkspecs/features/exclusive_builds.prf:
/usr/lib/qt/mkspecs/features/toolchain.prf:
/usr/lib/qt/mkspecs/features/default_pre.prf:
/usr/lib/qt/mkspecs/features/resolve_config.prf:
/usr/lib/qt/mkspecs/features/default_post.prf:
/usr/lib/qt/mkspecs/features/warn_on.prf:
/usr/lib/qt/mkspecs/features/qt.prf:
/usr/lib/qt/mkspecs/features/resources_functions.prf:
/usr/lib/qt/mkspecs/features/resources.prf:
/usr/lib/qt/mkspecs/features/moc.prf:
/usr/lib/qt/mkspecs/features/unix/opengl.prf:
/usr/lib/qt/mkspecs/features/uic.prf:
/usr/lib/qt/mkspecs/features/unix/thread.prf:
/usr/lib/qt/mkspecs/features/qmake_use.prf:
/usr/lib/qt/mkspecs/features/file_copies.prf:
/usr/lib/qt/mkspecs/features/testcase_targets.prf:
/usr/lib/qt/mkspecs/features/exceptions.prf:
/usr/lib/qt/mkspecs/features/yacc.prf:
/usr/lib/qt/mkspecs/features/lex.prf:
WeBookClient.pro:
WeBookClient.qrc:
qmake: FORCE
	@$(QMAKE) -o Makefile WeBookClient.pro

qmake_all: FORCE


all: Makefile build/debug/WeBookClient

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/
	$(COPY_FILE) --parents WeBookClient.qrc $(DISTDIR)/
	$(COPY_FILE) --parents /usr/lib/qt/mkspecs/features/data/dummy.cpp $(DISTDIR)/
	$(COPY_FILE) --parents src/AboutDialog.h src/MainWindow.h src/WeBookMan.h src/TreeItem.h src/TreeModel.h src/TreeViewDragDropModel.h src/QLogger/QLoggerLevel.h src/QLogger/QLoggerConstants.h src/QLogger/QLoggerManager.h src/QLogger/QLoggerWriter.h src/QLogger/QLoggerCommon.h src/QLogger/QLoggerCrypto.h src/QtAES/QAESEncryption.h $(DISTDIR)/
	$(COPY_FILE) --parents src/AboutDialog.cpp src/MainWindow.cpp src/WeBookMan.cpp src/TreeItem.cpp src/TreeModel.cpp src/TreeViewDragDropModel.cpp src/main.cpp src/QLogger/QLoggerManager.cpp src/QLogger/QLoggerWriter.cpp src/QLogger/QLoggerCommon.cpp src/QLogger/QLoggerCrypto.cpp src/QtAES/QAESEncryption.cpp $(DISTDIR)/
	$(COPY_FILE) --parents src/MainWindow.ui src/AboutDialog.ui $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


####### Sub-libraries

mocclean: compiler_moc_header_clean compiler_moc_objc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_objc_header_make_all compiler_moc_source_make_all

check: first

benchmark: first

compiler_rcc_make_all: build/debug/qrc/qrc_WeBookClient.cpp
compiler_rcc_clean:
	-$(DEL_FILE) build/debug/qrc/qrc_WeBookClient.cpp
build/debug/qrc/qrc_WeBookClient.cpp: WeBookClient.qrc \
		/usr/bin/rcc \
		README.md \
		images/logo32.png \
		images/win/wizardwand.png \
		images/win/clock.png \
		images/win/yinyang.png \
		images/win/usergroup.png \
		images/win/full_basket.png \
		images/win/wireless.png \
		images/win/comment.png \
		images/win/textcenter.png \
		images/win/left.png \
		images/win/editcut.png \
		images/win/fileprint.png \
		images/win/saveas.png \
		images/win/handshake.png \
		images/win/textbold.png \
		images/win/editcopy.png \
		images/win/checkbox-checked.png \
		images/win/format-indent-less.png \
		images/win/textunder.png \
		images/win/telephone.png \
		images/win/gear.png \
		images/win/notes.png \
		images/win/colorwheel.png \
		images/win/exit_button.png \
		images/win/textleft.png \
		images/win/phone.png \
		images/win/trash.png \
		images/win/lists.png \
		images/win/disconnect.png \
		images/win/exportpdf.png \
		images/win/upload.png \
		images/win/textitalic.png \
		images/win/checkbox.png \
		images/win/zoomout.png \
		images/win/date.png \
		images/win/hierarchy.png \
		images/win/openlock.png \
		images/win/camera.png \
		images/win/safe.png \
		images/win/textright.png \
		images/win/clipboard.png \
		images/win/remove_from_basket.png \
		images/win/fileopen.png \
		images/win/lock.png \
		images/win/editpaste.png \
		images/win/calculator.png \
		images/win/online.png \
		images/win/editundo.png \
		images/win/filesave.png \
		images/win/stop.png \
		images/win/opendoor.png \
		images/win/numberedlist.png \
		images/win/key.png \
		images/win/refresh.png \
		images/win/up.png \
		images/win/thumbsup.png \
		images/win/zoomin.png \
		images/win/format-indent-more.png \
		images/win/exit.png \
		images/win/box.png \
		images/win/addressbook.png \
		images/win/unlock.png \
		images/win/filenew.png \
		images/win/music.png \
		images/win/mail.png \
		images/win/editredo.png \
		images/win/cable.png \
		images/win/textjustify.png \
		images/win/connect.png \
		images/win/zoom.png \
		images/mac/wizardwand.png \
		images/mac/clock.png \
		images/mac/yinyang.png \
		images/mac/usergroup.png \
		images/mac/full_basket.png \
		images/mac/wireless.png \
		images/mac/comment.png \
		images/mac/textcenter.png \
		images/mac/left.png \
		images/mac/editcut.png \
		images/mac/fileprint.png \
		images/mac/saveas.png \
		images/mac/handshake.png \
		images/mac/textbold.png \
		images/mac/editcopy.png \
		images/mac/checkbox-checked.png \
		images/mac/format-indent-less.png \
		images/mac/textunder.png \
		images/mac/telephone.png \
		images/mac/gear.png \
		images/mac/notes.png \
		images/mac/colorwheel.png \
		images/mac/exit_button.png \
		images/mac/textleft.png \
		images/mac/phone.png \
		images/mac/trash.png \
		images/mac/lists.png \
		images/mac/disconnect.png \
		images/mac/exportpdf.png \
		images/mac/upload.png \
		images/mac/textitalic.png \
		images/mac/checkbox.png \
		images/mac/zoomout.png \
		images/mac/date.png \
		images/mac/hierarchy.png \
		images/mac/openlock.png \
		images/mac/camera.png \
		images/mac/safe.png \
		images/mac/textright.png \
		images/mac/clipboard.png \
		images/mac/remove_from_basket.png \
		images/mac/fileopen.png \
		images/mac/lock.png \
		images/mac/editpaste.png \
		images/mac/calculator.png \
		images/mac/online.png \
		images/mac/editundo.png \
		images/mac/filesave.png \
		images/mac/stop.png \
		images/mac/opendoor.png \
		images/mac/numberedlist.png \
		images/mac/key.png \
		images/mac/refresh.png \
		images/mac/up.png \
		images/mac/thumbsup.png \
		images/mac/zoomin.png \
		images/mac/format-indent-more.png \
		images/mac/exit.png \
		images/mac/box.png \
		images/mac/addressbook.png \
		images/mac/unlock.png \
		images/mac/filenew.png \
		images/mac/music.png \
		images/mac/mail.png \
		images/mac/editredo.png \
		images/mac/cable.png \
		images/mac/textjustify.png \
		images/mac/connect.png \
		images/mac/zoom.png
	/usr/bin/rcc -name WeBookClient WeBookClient.qrc -o build/debug/qrc/qrc_WeBookClient.cpp

compiler_moc_predefs_make_all: build/debug/moc/moc_predefs.h
compiler_moc_predefs_clean:
	-$(DEL_FILE) build/debug/moc/moc_predefs.h
build/debug/moc/moc_predefs.h: /usr/lib/qt/mkspecs/features/data/dummy.cpp
	g++ -pipe -O2 -std=gnu++1z -Wall -Wextra -dM -E -o build/debug/moc/moc_predefs.h /usr/lib/qt/mkspecs/features/data/dummy.cpp

compiler_moc_header_make_all: build/debug/moc/moc_AboutDialog.cpp build/debug/moc/moc_MainWindow.cpp build/debug/moc/moc_WeBookMan.cpp build/debug/moc/moc_TreeModel.cpp build/debug/moc/moc_TreeViewDragDropModel.cpp build/debug/moc/moc_QLoggerLevel.cpp build/debug/moc/moc_QLoggerWriter.cpp build/debug/moc/moc_QLoggerCommon.cpp build/debug/moc/moc_QLoggerCrypto.cpp build/debug/moc/moc_QAESEncryption.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) build/debug/moc/moc_AboutDialog.cpp build/debug/moc/moc_MainWindow.cpp build/debug/moc/moc_WeBookMan.cpp build/debug/moc/moc_TreeModel.cpp build/debug/moc/moc_TreeViewDragDropModel.cpp build/debug/moc/moc_QLoggerLevel.cpp build/debug/moc/moc_QLoggerWriter.cpp build/debug/moc/moc_QLoggerCommon.cpp build/debug/moc/moc_QLoggerCrypto.cpp build/debug/moc/moc_QAESEncryption.cpp
build/debug/moc/moc_AboutDialog.cpp: src/AboutDialog.h \
		build/debug/ui/ui_AboutDialog.h \
		build/debug/moc/moc_predefs.h \
		/usr/bin/moc
	/usr/bin/moc $(DEFINES) --include /mnt/qnap-light-wizzard/workspace/WeBook/projects/WeBookClient/build/debug/moc/moc_predefs.h -I/usr/lib/qt/mkspecs/linux-g++ -I/mnt/qnap-light-wizzard/workspace/WeBook/projects/WeBookClient -I/mnt/qnap-light-wizzard/workspace/WeBook/projects/WeBookClient -I/mnt/qnap-light-wizzard/workspace/WeBook/projects/WeBookClient/src -I'/mnt/qnap-light-wizzard/workspace/WeBook/projects/WeBookClient/${QT_INSTALL_LIBS}/qt' -I/mnt/qnap-light-wizzard/workspace/WeBook/projects/WeBookClient/src/QtAES -I/usr/include/qt -I/usr/include/qt/QtPrintSupport -I/usr/include/qt/QtWidgets -I/usr/include/qt/QtGui -I/usr/include/qt/QtNetwork -I/usr/include/qt/QtCore -I/usr/include/c++/9.3.0 -I/usr/include/c++/9.3.0/x86_64-pc-linux-gnu -I/usr/include/c++/9.3.0/backward -I/usr/lib/gcc/x86_64-pc-linux-gnu/9.3.0/include -I/usr/local/include -I/usr/lib/gcc/x86_64-pc-linux-gnu/9.3.0/include-fixed -I/usr/include src/AboutDialog.h -o build/debug/moc/moc_AboutDialog.cpp

build/debug/moc/moc_MainWindow.cpp: src/MainWindow.h \
		src/QLogger/QLoggerCommon.h \
		src/QLogger/QLoggerConstants.h \
		src/QLogger/QLoggerLevel.h \
		src/QLogger/QLoggerManager.h \
		src/QLogger/QLoggerWriter.h \
		src/QLogger/QLoggerCrypto.h \
		src/QtAES/QAESEncryption.h \
		src/WeBookMan.h \
		src/TreeModel.h \
		src/TreeItem.h \
		src/TreeViewDragDropModel.h \
		src/AboutDialog.h \
		build/debug/ui/ui_AboutDialog.h \
		build/debug/ui/ui_MainWindow.h \
		build/debug/moc/moc_predefs.h \
		/usr/bin/moc
	/usr/bin/moc $(DEFINES) --include /mnt/qnap-light-wizzard/workspace/WeBook/projects/WeBookClient/build/debug/moc/moc_predefs.h -I/usr/lib/qt/mkspecs/linux-g++ -I/mnt/qnap-light-wizzard/workspace/WeBook/projects/WeBookClient -I/mnt/qnap-light-wizzard/workspace/WeBook/projects/WeBookClient -I/mnt/qnap-light-wizzard/workspace/WeBook/projects/WeBookClient/src -I'/mnt/qnap-light-wizzard/workspace/WeBook/projects/WeBookClient/${QT_INSTALL_LIBS}/qt' -I/mnt/qnap-light-wizzard/workspace/WeBook/projects/WeBookClient/src/QtAES -I/usr/include/qt -I/usr/include/qt/QtPrintSupport -I/usr/include/qt/QtWidgets -I/usr/include/qt/QtGui -I/usr/include/qt/QtNetwork -I/usr/include/qt/QtCore -I/usr/include/c++/9.3.0 -I/usr/include/c++/9.3.0/x86_64-pc-linux-gnu -I/usr/include/c++/9.3.0/backward -I/usr/lib/gcc/x86_64-pc-linux-gnu/9.3.0/include -I/usr/local/include -I/usr/lib/gcc/x86_64-pc-linux-gnu/9.3.0/include-fixed -I/usr/include src/MainWindow.h -o build/debug/moc/moc_MainWindow.cpp

build/debug/moc/moc_WeBookMan.cpp: src/WeBookMan.h \
		src/QLogger/QLoggerCommon.h \
		src/QLogger/QLoggerConstants.h \
		src/QLogger/QLoggerLevel.h \
		src/QLogger/QLoggerManager.h \
		src/QLogger/QLoggerWriter.h \
		build/debug/moc/moc_predefs.h \
		/usr/bin/moc
	/usr/bin/moc $(DEFINES) --include /mnt/qnap-light-wizzard/workspace/WeBook/projects/WeBookClient/build/debug/moc/moc_predefs.h -I/usr/lib/qt/mkspecs/linux-g++ -I/mnt/qnap-light-wizzard/workspace/WeBook/projects/WeBookClient -I/mnt/qnap-light-wizzard/workspace/WeBook/projects/WeBookClient -I/mnt/qnap-light-wizzard/workspace/WeBook/projects/WeBookClient/src -I'/mnt/qnap-light-wizzard/workspace/WeBook/projects/WeBookClient/${QT_INSTALL_LIBS}/qt' -I/mnt/qnap-light-wizzard/workspace/WeBook/projects/WeBookClient/src/QtAES -I/usr/include/qt -I/usr/include/qt/QtPrintSupport -I/usr/include/qt/QtWidgets -I/usr/include/qt/QtGui -I/usr/include/qt/QtNetwork -I/usr/include/qt/QtCore -I/usr/include/c++/9.3.0 -I/usr/include/c++/9.3.0/x86_64-pc-linux-gnu -I/usr/include/c++/9.3.0/backward -I/usr/lib/gcc/x86_64-pc-linux-gnu/9.3.0/include -I/usr/local/include -I/usr/lib/gcc/x86_64-pc-linux-gnu/9.3.0/include-fixed -I/usr/include src/WeBookMan.h -o build/debug/moc/moc_WeBookMan.cpp

build/debug/moc/moc_TreeModel.cpp: src/TreeModel.h \
		src/QLogger/QLoggerCommon.h \
		src/QLogger/QLoggerConstants.h \
		src/QLogger/QLoggerLevel.h \
		src/QLogger/QLoggerManager.h \
		src/QLogger/QLoggerWriter.h \
		src/TreeItem.h \
		build/debug/moc/moc_predefs.h \
		/usr/bin/moc
	/usr/bin/moc $(DEFINES) --include /mnt/qnap-light-wizzard/workspace/WeBook/projects/WeBookClient/build/debug/moc/moc_predefs.h -I/usr/lib/qt/mkspecs/linux-g++ -I/mnt/qnap-light-wizzard/workspace/WeBook/projects/WeBookClient -I/mnt/qnap-light-wizzard/workspace/WeBook/projects/WeBookClient -I/mnt/qnap-light-wizzard/workspace/WeBook/projects/WeBookClient/src -I'/mnt/qnap-light-wizzard/workspace/WeBook/projects/WeBookClient/${QT_INSTALL_LIBS}/qt' -I/mnt/qnap-light-wizzard/workspace/WeBook/projects/WeBookClient/src/QtAES -I/usr/include/qt -I/usr/include/qt/QtPrintSupport -I/usr/include/qt/QtWidgets -I/usr/include/qt/QtGui -I/usr/include/qt/QtNetwork -I/usr/include/qt/QtCore -I/usr/include/c++/9.3.0 -I/usr/include/c++/9.3.0/x86_64-pc-linux-gnu -I/usr/include/c++/9.3.0/backward -I/usr/lib/gcc/x86_64-pc-linux-gnu/9.3.0/include -I/usr/local/include -I/usr/lib/gcc/x86_64-pc-linux-gnu/9.3.0/include-fixed -I/usr/include src/TreeModel.h -o build/debug/moc/moc_TreeModel.cpp

build/debug/moc/moc_TreeViewDragDropModel.cpp: src/TreeViewDragDropModel.h \
		src/QLogger/QLoggerCommon.h \
		src/QLogger/QLoggerConstants.h \
		src/QLogger/QLoggerLevel.h \
		src/QLogger/QLoggerManager.h \
		src/QLogger/QLoggerWriter.h \
		src/TreeModel.h \
		src/TreeItem.h \
		build/debug/moc/moc_predefs.h \
		/usr/bin/moc
	/usr/bin/moc $(DEFINES) --include /mnt/qnap-light-wizzard/workspace/WeBook/projects/WeBookClient/build/debug/moc/moc_predefs.h -I/usr/lib/qt/mkspecs/linux-g++ -I/mnt/qnap-light-wizzard/workspace/WeBook/projects/WeBookClient -I/mnt/qnap-light-wizzard/workspace/WeBook/projects/WeBookClient -I/mnt/qnap-light-wizzard/workspace/WeBook/projects/WeBookClient/src -I'/mnt/qnap-light-wizzard/workspace/WeBook/projects/WeBookClient/${QT_INSTALL_LIBS}/qt' -I/mnt/qnap-light-wizzard/workspace/WeBook/projects/WeBookClient/src/QtAES -I/usr/include/qt -I/usr/include/qt/QtPrintSupport -I/usr/include/qt/QtWidgets -I/usr/include/qt/QtGui -I/usr/include/qt/QtNetwork -I/usr/include/qt/QtCore -I/usr/include/c++/9.3.0 -I/usr/include/c++/9.3.0/x86_64-pc-linux-gnu -I/usr/include/c++/9.3.0/backward -I/usr/lib/gcc/x86_64-pc-linux-gnu/9.3.0/include -I/usr/local/include -I/usr/lib/gcc/x86_64-pc-linux-gnu/9.3.0/include-fixed -I/usr/include src/TreeViewDragDropModel.h -o build/debug/moc/moc_TreeViewDragDropModel.cpp

build/debug/moc/moc_QLoggerLevel.cpp: src/QLogger/QLoggerLevel.h \
		build/debug/moc/moc_predefs.h \
		/usr/bin/moc
	/usr/bin/moc $(DEFINES) --include /mnt/qnap-light-wizzard/workspace/WeBook/projects/WeBookClient/build/debug/moc/moc_predefs.h -I/usr/lib/qt/mkspecs/linux-g++ -I/mnt/qnap-light-wizzard/workspace/WeBook/projects/WeBookClient -I/mnt/qnap-light-wizzard/workspace/WeBook/projects/WeBookClient -I/mnt/qnap-light-wizzard/workspace/WeBook/projects/WeBookClient/src -I'/mnt/qnap-light-wizzard/workspace/WeBook/projects/WeBookClient/${QT_INSTALL_LIBS}/qt' -I/mnt/qnap-light-wizzard/workspace/WeBook/projects/WeBookClient/src/QtAES -I/usr/include/qt -I/usr/include/qt/QtPrintSupport -I/usr/include/qt/QtWidgets -I/usr/include/qt/QtGui -I/usr/include/qt/QtNetwork -I/usr/include/qt/QtCore -I/usr/include/c++/9.3.0 -I/usr/include/c++/9.3.0/x86_64-pc-linux-gnu -I/usr/include/c++/9.3.0/backward -I/usr/lib/gcc/x86_64-pc-linux-gnu/9.3.0/include -I/usr/local/include -I/usr/lib/gcc/x86_64-pc-linux-gnu/9.3.0/include-fixed -I/usr/include src/QLogger/QLoggerLevel.h -o build/debug/moc/moc_QLoggerLevel.cpp

build/debug/moc/moc_QLoggerWriter.cpp: src/QLogger/QLoggerWriter.h \
		src/QLogger/QLoggerLevel.h \
		build/debug/moc/moc_predefs.h \
		/usr/bin/moc
	/usr/bin/moc $(DEFINES) --include /mnt/qnap-light-wizzard/workspace/WeBook/projects/WeBookClient/build/debug/moc/moc_predefs.h -I/usr/lib/qt/mkspecs/linux-g++ -I/mnt/qnap-light-wizzard/workspace/WeBook/projects/WeBookClient -I/mnt/qnap-light-wizzard/workspace/WeBook/projects/WeBookClient -I/mnt/qnap-light-wizzard/workspace/WeBook/projects/WeBookClient/src -I'/mnt/qnap-light-wizzard/workspace/WeBook/projects/WeBookClient/${QT_INSTALL_LIBS}/qt' -I/mnt/qnap-light-wizzard/workspace/WeBook/projects/WeBookClient/src/QtAES -I/usr/include/qt -I/usr/include/qt/QtPrintSupport -I/usr/include/qt/QtWidgets -I/usr/include/qt/QtGui -I/usr/include/qt/QtNetwork -I/usr/include/qt/QtCore -I/usr/include/c++/9.3.0 -I/usr/include/c++/9.3.0/x86_64-pc-linux-gnu -I/usr/include/c++/9.3.0/backward -I/usr/lib/gcc/x86_64-pc-linux-gnu/9.3.0/include -I/usr/local/include -I/usr/lib/gcc/x86_64-pc-linux-gnu/9.3.0/include-fixed -I/usr/include src/QLogger/QLoggerWriter.h -o build/debug/moc/moc_QLoggerWriter.cpp

build/debug/moc/moc_QLoggerCommon.cpp: src/QLogger/QLoggerCommon.h \
		src/QLogger/QLoggerConstants.h \
		src/QLogger/QLoggerLevel.h \
		src/QLogger/QLoggerManager.h \
		src/QLogger/QLoggerWriter.h \
		build/debug/moc/moc_predefs.h \
		/usr/bin/moc
	/usr/bin/moc $(DEFINES) --include /mnt/qnap-light-wizzard/workspace/WeBook/projects/WeBookClient/build/debug/moc/moc_predefs.h -I/usr/lib/qt/mkspecs/linux-g++ -I/mnt/qnap-light-wizzard/workspace/WeBook/projects/WeBookClient -I/mnt/qnap-light-wizzard/workspace/WeBook/projects/WeBookClient -I/mnt/qnap-light-wizzard/workspace/WeBook/projects/WeBookClient/src -I'/mnt/qnap-light-wizzard/workspace/WeBook/projects/WeBookClient/${QT_INSTALL_LIBS}/qt' -I/mnt/qnap-light-wizzard/workspace/WeBook/projects/WeBookClient/src/QtAES -I/usr/include/qt -I/usr/include/qt/QtPrintSupport -I/usr/include/qt/QtWidgets -I/usr/include/qt/QtGui -I/usr/include/qt/QtNetwork -I/usr/include/qt/QtCore -I/usr/include/c++/9.3.0 -I/usr/include/c++/9.3.0/x86_64-pc-linux-gnu -I/usr/include/c++/9.3.0/backward -I/usr/lib/gcc/x86_64-pc-linux-gnu/9.3.0/include -I/usr/local/include -I/usr/lib/gcc/x86_64-pc-linux-gnu/9.3.0/include-fixed -I/usr/include src/QLogger/QLoggerCommon.h -o build/debug/moc/moc_QLoggerCommon.cpp

build/debug/moc/moc_QLoggerCrypto.cpp: src/QLogger/QLoggerCrypto.h \
		src/QLogger/QLoggerCommon.h \
		src/QLogger/QLoggerConstants.h \
		src/QLogger/QLoggerLevel.h \
		src/QLogger/QLoggerManager.h \
		src/QLogger/QLoggerWriter.h \
		src/QtAES/QAESEncryption.h \
		build/debug/moc/moc_predefs.h \
		/usr/bin/moc
	/usr/bin/moc $(DEFINES) --include /mnt/qnap-light-wizzard/workspace/WeBook/projects/WeBookClient/build/debug/moc/moc_predefs.h -I/usr/lib/qt/mkspecs/linux-g++ -I/mnt/qnap-light-wizzard/workspace/WeBook/projects/WeBookClient -I/mnt/qnap-light-wizzard/workspace/WeBook/projects/WeBookClient -I/mnt/qnap-light-wizzard/workspace/WeBook/projects/WeBookClient/src -I'/mnt/qnap-light-wizzard/workspace/WeBook/projects/WeBookClient/${QT_INSTALL_LIBS}/qt' -I/mnt/qnap-light-wizzard/workspace/WeBook/projects/WeBookClient/src/QtAES -I/usr/include/qt -I/usr/include/qt/QtPrintSupport -I/usr/include/qt/QtWidgets -I/usr/include/qt/QtGui -I/usr/include/qt/QtNetwork -I/usr/include/qt/QtCore -I/usr/include/c++/9.3.0 -I/usr/include/c++/9.3.0/x86_64-pc-linux-gnu -I/usr/include/c++/9.3.0/backward -I/usr/lib/gcc/x86_64-pc-linux-gnu/9.3.0/include -I/usr/local/include -I/usr/lib/gcc/x86_64-pc-linux-gnu/9.3.0/include-fixed -I/usr/include src/QLogger/QLoggerCrypto.h -o build/debug/moc/moc_QLoggerCrypto.cpp

build/debug/moc/moc_QAESEncryption.cpp: src/QtAES/QAESEncryption.h \
		build/debug/moc/moc_predefs.h \
		/usr/bin/moc
	/usr/bin/moc $(DEFINES) --include /mnt/qnap-light-wizzard/workspace/WeBook/projects/WeBookClient/build/debug/moc/moc_predefs.h -I/usr/lib/qt/mkspecs/linux-g++ -I/mnt/qnap-light-wizzard/workspace/WeBook/projects/WeBookClient -I/mnt/qnap-light-wizzard/workspace/WeBook/projects/WeBookClient -I/mnt/qnap-light-wizzard/workspace/WeBook/projects/WeBookClient/src -I'/mnt/qnap-light-wizzard/workspace/WeBook/projects/WeBookClient/${QT_INSTALL_LIBS}/qt' -I/mnt/qnap-light-wizzard/workspace/WeBook/projects/WeBookClient/src/QtAES -I/usr/include/qt -I/usr/include/qt/QtPrintSupport -I/usr/include/qt/QtWidgets -I/usr/include/qt/QtGui -I/usr/include/qt/QtNetwork -I/usr/include/qt/QtCore -I/usr/include/c++/9.3.0 -I/usr/include/c++/9.3.0/x86_64-pc-linux-gnu -I/usr/include/c++/9.3.0/backward -I/usr/lib/gcc/x86_64-pc-linux-gnu/9.3.0/include -I/usr/local/include -I/usr/lib/gcc/x86_64-pc-linux-gnu/9.3.0/include-fixed -I/usr/include src/QtAES/QAESEncryption.h -o build/debug/moc/moc_QAESEncryption.cpp

compiler_moc_objc_header_make_all:
compiler_moc_objc_header_clean:
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: build/debug/ui/ui_MainWindow.h build/debug/ui/ui_AboutDialog.h
compiler_uic_clean:
	-$(DEL_FILE) build/debug/ui/ui_MainWindow.h build/debug/ui/ui_AboutDialog.h
build/debug/ui/ui_MainWindow.h: src/MainWindow.ui \
		/usr/bin/uic
	/usr/bin/uic src/MainWindow.ui -o build/debug/ui/ui_MainWindow.h

build/debug/ui/ui_AboutDialog.h: src/AboutDialog.ui \
		/usr/bin/uic
	/usr/bin/uic src/AboutDialog.ui -o build/debug/ui/ui_AboutDialog.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_rcc_clean compiler_moc_predefs_clean compiler_moc_header_clean compiler_uic_clean 

####### Compile

build/debug/obj/AboutDialog.o: src/AboutDialog.cpp src/AboutDialog.h \
		build/debug/ui/ui_AboutDialog.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/debug/obj/AboutDialog.o src/AboutDialog.cpp

build/debug/obj/MainWindow.o: src/MainWindow.cpp src/MainWindow.h \
		src/QLogger/QLoggerCommon.h \
		src/QLogger/QLoggerConstants.h \
		src/QLogger/QLoggerLevel.h \
		src/QLogger/QLoggerManager.h \
		src/QLogger/QLoggerWriter.h \
		src/QLogger/QLoggerCrypto.h \
		src/QtAES/QAESEncryption.h \
		src/WeBookMan.h \
		src/TreeModel.h \
		src/TreeItem.h \
		src/TreeViewDragDropModel.h \
		src/AboutDialog.h \
		build/debug/ui/ui_AboutDialog.h \
		build/debug/ui/ui_MainWindow.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/debug/obj/MainWindow.o src/MainWindow.cpp

build/debug/obj/WeBookMan.o: src/WeBookMan.cpp src/WeBookMan.h \
		src/QLogger/QLoggerCommon.h \
		src/QLogger/QLoggerConstants.h \
		src/QLogger/QLoggerLevel.h \
		src/QLogger/QLoggerManager.h \
		src/QLogger/QLoggerWriter.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/debug/obj/WeBookMan.o src/WeBookMan.cpp

build/debug/obj/TreeItem.o: src/TreeItem.cpp src/TreeItem.h \
		src/QLogger/QLoggerCommon.h \
		src/QLogger/QLoggerConstants.h \
		src/QLogger/QLoggerLevel.h \
		src/QLogger/QLoggerManager.h \
		src/QLogger/QLoggerWriter.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/debug/obj/TreeItem.o src/TreeItem.cpp

build/debug/obj/TreeModel.o: src/TreeModel.cpp src/TreeModel.h \
		src/QLogger/QLoggerCommon.h \
		src/QLogger/QLoggerConstants.h \
		src/QLogger/QLoggerLevel.h \
		src/QLogger/QLoggerManager.h \
		src/QLogger/QLoggerWriter.h \
		src/TreeItem.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/debug/obj/TreeModel.o src/TreeModel.cpp

build/debug/obj/TreeViewDragDropModel.o: src/TreeViewDragDropModel.cpp src/TreeViewDragDropModel.h \
		src/QLogger/QLoggerCommon.h \
		src/QLogger/QLoggerConstants.h \
		src/QLogger/QLoggerLevel.h \
		src/QLogger/QLoggerManager.h \
		src/QLogger/QLoggerWriter.h \
		src/TreeModel.h \
		src/TreeItem.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/debug/obj/TreeViewDragDropModel.o src/TreeViewDragDropModel.cpp

build/debug/obj/main.o: src/main.cpp src/MainWindow.h \
		src/QLogger/QLoggerCommon.h \
		src/QLogger/QLoggerConstants.h \
		src/QLogger/QLoggerLevel.h \
		src/QLogger/QLoggerManager.h \
		src/QLogger/QLoggerWriter.h \
		src/QLogger/QLoggerCrypto.h \
		src/QtAES/QAESEncryption.h \
		src/WeBookMan.h \
		src/TreeModel.h \
		src/TreeItem.h \
		src/TreeViewDragDropModel.h \
		src/AboutDialog.h \
		build/debug/ui/ui_AboutDialog.h \
		build/debug/ui/ui_MainWindow.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/debug/obj/main.o src/main.cpp

build/debug/obj/QLoggerManager.o: src/QLogger/QLoggerManager.cpp src/QLogger/QLoggerManager.h \
		src/QLogger/QLoggerLevel.h \
		src/QLogger/QLoggerWriter.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/debug/obj/QLoggerManager.o src/QLogger/QLoggerManager.cpp

build/debug/obj/QLoggerWriter.o: src/QLogger/QLoggerWriter.cpp src/QLogger/QLoggerWriter.h \
		src/QLogger/QLoggerLevel.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/debug/obj/QLoggerWriter.o src/QLogger/QLoggerWriter.cpp

build/debug/obj/QLoggerCommon.o: src/QLogger/QLoggerCommon.cpp src/QLogger/QLoggerCommon.h \
		src/QLogger/QLoggerConstants.h \
		src/QLogger/QLoggerLevel.h \
		src/QLogger/QLoggerManager.h \
		src/QLogger/QLoggerWriter.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/debug/obj/QLoggerCommon.o src/QLogger/QLoggerCommon.cpp

build/debug/obj/QLoggerCrypto.o: src/QLogger/QLoggerCrypto.cpp src/QLogger/QLoggerCrypto.h \
		src/QLogger/QLoggerCommon.h \
		src/QLogger/QLoggerConstants.h \
		src/QLogger/QLoggerLevel.h \
		src/QLogger/QLoggerManager.h \
		src/QLogger/QLoggerWriter.h \
		src/QtAES/QAESEncryption.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/debug/obj/QLoggerCrypto.o src/QLogger/QLoggerCrypto.cpp

build/debug/obj/QAESEncryption.o: src/QtAES/QAESEncryption.cpp src/QtAES/QAESEncryption.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/debug/obj/QAESEncryption.o src/QtAES/QAESEncryption.cpp

build/debug/obj/qrc_WeBookClient.o: build/debug/qrc/qrc_WeBookClient.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/debug/obj/qrc_WeBookClient.o build/debug/qrc/qrc_WeBookClient.cpp

build/debug/obj/moc_AboutDialog.o: build/debug/moc/moc_AboutDialog.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/debug/obj/moc_AboutDialog.o build/debug/moc/moc_AboutDialog.cpp

build/debug/obj/moc_MainWindow.o: build/debug/moc/moc_MainWindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/debug/obj/moc_MainWindow.o build/debug/moc/moc_MainWindow.cpp

build/debug/obj/moc_WeBookMan.o: build/debug/moc/moc_WeBookMan.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/debug/obj/moc_WeBookMan.o build/debug/moc/moc_WeBookMan.cpp

build/debug/obj/moc_TreeModel.o: build/debug/moc/moc_TreeModel.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/debug/obj/moc_TreeModel.o build/debug/moc/moc_TreeModel.cpp

build/debug/obj/moc_TreeViewDragDropModel.o: build/debug/moc/moc_TreeViewDragDropModel.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/debug/obj/moc_TreeViewDragDropModel.o build/debug/moc/moc_TreeViewDragDropModel.cpp

build/debug/obj/moc_QLoggerLevel.o: build/debug/moc/moc_QLoggerLevel.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/debug/obj/moc_QLoggerLevel.o build/debug/moc/moc_QLoggerLevel.cpp

build/debug/obj/moc_QLoggerWriter.o: build/debug/moc/moc_QLoggerWriter.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/debug/obj/moc_QLoggerWriter.o build/debug/moc/moc_QLoggerWriter.cpp

build/debug/obj/moc_QLoggerCommon.o: build/debug/moc/moc_QLoggerCommon.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/debug/obj/moc_QLoggerCommon.o build/debug/moc/moc_QLoggerCommon.cpp

build/debug/obj/moc_QLoggerCrypto.o: build/debug/moc/moc_QLoggerCrypto.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/debug/obj/moc_QLoggerCrypto.o build/debug/moc/moc_QLoggerCrypto.cpp

build/debug/obj/moc_QAESEncryption.o: build/debug/moc/moc_QAESEncryption.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/debug/obj/moc_QAESEncryption.o build/debug/moc/moc_QAESEncryption.cpp

####### Install

install_shortcutfiles: first FORCE
	@test -d $(INSTALL_ROOT)/mnt/qnap-light-wizzard/workspace/WeBook/projects/WeBookClient/usr/share/applications || mkdir -p $(INSTALL_ROOT)/mnt/qnap-light-wizzard/workspace/WeBook/projects/WeBookClient/usr/share/applications
	$(QINSTALL_PROGRAM) /mnt/qnap-light-wizzard/workspace/WeBook/projects/WeBookClient/usr/share/applications/WeBookClient.desktop $(INSTALL_ROOT)/mnt/qnap-light-wizzard/workspace/WeBook/projects/WeBookClient/usr/share/applications/WeBookClient.desktop
	-strip $(INSTALL_ROOT)/mnt/qnap-light-wizzard/workspace/WeBook/projects/WeBookClient/usr/share/applications/WeBookClient.desktop

uninstall_shortcutfiles: FORCE
	-$(DEL_FILE) -r $(INSTALL_ROOT)/mnt/qnap-light-wizzard/workspace/WeBook/projects/WeBookClient/usr/share/applications/WeBookClient.desktop
	-$(DEL_DIR) $(INSTALL_ROOT)/mnt/qnap-light-wizzard/workspace/WeBook/projects/WeBookClient/usr/share/applications/ 


install_data: first FORCE
	@test -d $(INSTALL_ROOT)/mnt/qnap-light-wizzard/workspace/WeBook/projects/WeBookClient/usr/share/pixmaps || mkdir -p $(INSTALL_ROOT)/mnt/qnap-light-wizzard/workspace/WeBook/projects/WeBookClient/usr/share/pixmaps
	$(QINSTALL_PROGRAM) /mnt/qnap-light-wizzard/workspace/WeBook/projects/WeBookClient/usr/share/icons/hicolor/48x48/apps/WeBookClient.png $(INSTALL_ROOT)/mnt/qnap-light-wizzard/workspace/WeBook/projects/WeBookClient/usr/share/pixmaps/WeBookClient.png
	-strip $(INSTALL_ROOT)/mnt/qnap-light-wizzard/workspace/WeBook/projects/WeBookClient/usr/share/pixmaps/WeBookClient.png

uninstall_data: FORCE
	-$(DEL_FILE) -r $(INSTALL_ROOT)/mnt/qnap-light-wizzard/workspace/WeBook/projects/WeBookClient/usr/share/pixmaps/WeBookClient.png
	-$(DEL_DIR) $(INSTALL_ROOT)/mnt/qnap-light-wizzard/workspace/WeBook/projects/WeBookClient/usr/share/pixmaps/ 


install_target: first FORCE
	@test -d $(INSTALL_ROOT)/usr/bin || mkdir -p $(INSTALL_ROOT)/usr/bin
	$(QINSTALL_PROGRAM) build/debug/$(QMAKE_TARGET) $(INSTALL_ROOT)/usr/bin/$(QMAKE_TARGET)
	-$(STRIP) $(INSTALL_ROOT)/usr/bin/$(QMAKE_TARGET)

uninstall_target: FORCE
	-$(DEL_FILE) $(INSTALL_ROOT)/usr/bin/$(QMAKE_TARGET)
	-$(DEL_DIR) $(INSTALL_ROOT)/usr/bin/ 


install: install_shortcutfiles install_data install_target  FORCE

uninstall: uninstall_shortcutfiles uninstall_data uninstall_target  FORCE

FORCE:

